name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  build_site:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Pandoc
    - name: Install Pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc

    # Step 3: Run the custom build script
    - name: Build the site
      run: bash build.sh

    # Step 4: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs